# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 585c8c1f2c1e1d992de9492b3478cdb462efbcdb716ed2d2450373db63fb144866255d573ad3f6ae1c5d6c8b43a77cdf02302b72187e788359fbe7131f0308e2

test:
  secret_key_base: 0fa05e4457c016cccfa2469efd88d2efa5cd74b0104965055856246a73097cefd9c80370f6f5ec286fed6837a1e7225f203ce169273c59830bfec2b0329b7e62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
